# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import currency_pb2 as currency__pb2


class CurrenciesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.register = channel.unary_stream(
        '/currencies.Currencies/register',
        request_serializer=currency__pb2.BankInfo.SerializeToString,
        response_deserializer=currency__pb2.CurrencyInfo.FromString,
        )


class CurrenciesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CurrenciesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'register': grpc.unary_stream_rpc_method_handler(
          servicer.register,
          request_deserializer=currency__pb2.BankInfo.FromString,
          response_serializer=currency__pb2.CurrencyInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'currencies.Currencies', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
