# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: currency.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='currency.proto',
  package='currencies',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63urrency.proto\x12\ncurrencies\"7\n\x08\x42\x61nkInfo\x12+\n\rotherCurrency\x18\x02 \x03(\x0e\x32\x14.currencies.Currency\"E\n\x0c\x43urrencyInfo\x12&\n\x08\x63urrency\x18\x01 \x01(\x0e\x32\x14.currencies.Currency\x12\r\n\x05value\x18\x02 \x01(\x02*.\n\x08\x43urrency\x12\x07\n\x03USD\x10\x00\x12\x07\n\x03\x45UR\x10\x01\x12\x07\n\x03GBP\x10\x02\x12\x07\n\x03\x43HF\x10\x03\x32L\n\nCurrencies\x12>\n\x08register\x12\x14.currencies.BankInfo\x1a\x18.currencies.CurrencyInfo\"\x00\x30\x01\x62\x06proto3')
)

_CURRENCY = _descriptor.EnumDescriptor(
  name='Currency',
  full_name='currencies.Currency',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='USD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EUR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GBP', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHF', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=158,
  serialized_end=204,
)
_sym_db.RegisterEnumDescriptor(_CURRENCY)

Currency = enum_type_wrapper.EnumTypeWrapper(_CURRENCY)
USD = 0
EUR = 1
GBP = 2
CHF = 3



_BANKINFO = _descriptor.Descriptor(
  name='BankInfo',
  full_name='currencies.BankInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='otherCurrency', full_name='currencies.BankInfo.otherCurrency', index=0,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=85,
)


_CURRENCYINFO = _descriptor.Descriptor(
  name='CurrencyInfo',
  full_name='currencies.CurrencyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currency', full_name='currencies.CurrencyInfo.currency', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='currencies.CurrencyInfo.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=156,
)

_BANKINFO.fields_by_name['otherCurrency'].enum_type = _CURRENCY
_CURRENCYINFO.fields_by_name['currency'].enum_type = _CURRENCY
DESCRIPTOR.message_types_by_name['BankInfo'] = _BANKINFO
DESCRIPTOR.message_types_by_name['CurrencyInfo'] = _CURRENCYINFO
DESCRIPTOR.enum_types_by_name['Currency'] = _CURRENCY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BankInfo = _reflection.GeneratedProtocolMessageType('BankInfo', (_message.Message,), dict(
  DESCRIPTOR = _BANKINFO,
  __module__ = 'currency_pb2'
  # @@protoc_insertion_point(class_scope:currencies.BankInfo)
  ))
_sym_db.RegisterMessage(BankInfo)

CurrencyInfo = _reflection.GeneratedProtocolMessageType('CurrencyInfo', (_message.Message,), dict(
  DESCRIPTOR = _CURRENCYINFO,
  __module__ = 'currency_pb2'
  # @@protoc_insertion_point(class_scope:currencies.CurrencyInfo)
  ))
_sym_db.RegisterMessage(CurrencyInfo)



_CURRENCIES = _descriptor.ServiceDescriptor(
  name='Currencies',
  full_name='currencies.Currencies',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=206,
  serialized_end=282,
  methods=[
  _descriptor.MethodDescriptor(
    name='register',
    full_name='currencies.Currencies.register',
    index=0,
    containing_service=None,
    input_type=_BANKINFO,
    output_type=_CURRENCYINFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CURRENCIES)

DESCRIPTOR.services_by_name['Currencies'] = _CURRENCIES

# @@protoc_insertion_point(module_scope)
